# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hoangkplog/Desktop/CPP_Project/UTCalculateur

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hoangkplog/Desktop/CPP_Project/UTCalculateur

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/hoangkplog/Desktop/CPP_Project/UTCalculateur/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hoangkplog/Desktop/CPP_Project/UTCalculateur/CMakeFiles /home/hoangkplog/Desktop/CPP_Project/UTCalculateur/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hoangkplog/Desktop/CPP_Project/UTCalculateur/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UTCalculateur

# Build rule for target.
UTCalculateur: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UTCalculateur
.PHONY : UTCalculateur

# fast build rule for target.
UTCalculateur/fast:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/build
.PHONY : UTCalculateur/fast

#=============================================================================
# Target rules for targets named UTCalculateur_autogen

# Build rule for target.
UTCalculateur_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UTCalculateur_autogen
.PHONY : UTCalculateur_autogen

# fast build rule for target.
UTCalculateur_autogen/fast:
	$(MAKE) -f CMakeFiles/UTCalculateur_autogen.dir/build.make CMakeFiles/UTCalculateur_autogen.dir/build
.PHONY : UTCalculateur_autogen/fast

UTCalculateur_autogen/mocs_compilation.o: UTCalculateur_autogen/mocs_compilation.cpp.o

.PHONY : UTCalculateur_autogen/mocs_compilation.o

# target to build an object file
UTCalculateur_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/UTCalculateur_autogen/mocs_compilation.cpp.o
.PHONY : UTCalculateur_autogen/mocs_compilation.cpp.o

UTCalculateur_autogen/mocs_compilation.i: UTCalculateur_autogen/mocs_compilation.cpp.i

.PHONY : UTCalculateur_autogen/mocs_compilation.i

# target to preprocess a source file
UTCalculateur_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/UTCalculateur_autogen/mocs_compilation.cpp.i
.PHONY : UTCalculateur_autogen/mocs_compilation.cpp.i

UTCalculateur_autogen/mocs_compilation.s: UTCalculateur_autogen/mocs_compilation.cpp.s

.PHONY : UTCalculateur_autogen/mocs_compilation.s

# target to generate assembly for a file
UTCalculateur_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/UTCalculateur_autogen/mocs_compilation.cpp.s
.PHONY : UTCalculateur_autogen/mocs_compilation.cpp.s

src/controleur.o: src/controleur.cpp.o

.PHONY : src/controleur.o

# target to build an object file
src/controleur.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/controleur.cpp.o
.PHONY : src/controleur.cpp.o

src/controleur.i: src/controleur.cpp.i

.PHONY : src/controleur.i

# target to preprocess a source file
src/controleur.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/controleur.cpp.i
.PHONY : src/controleur.cpp.i

src/controleur.s: src/controleur.cpp.s

.PHONY : src/controleur.s

# target to generate assembly for a file
src/controleur.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/controleur.cpp.s
.PHONY : src/controleur.cpp.s

src/litterale.o: src/litterale.cpp.o

.PHONY : src/litterale.o

# target to build an object file
src/litterale.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale.cpp.o
.PHONY : src/litterale.cpp.o

src/litterale.i: src/litterale.cpp.i

.PHONY : src/litterale.i

# target to preprocess a source file
src/litterale.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale.cpp.i
.PHONY : src/litterale.cpp.i

src/litterale.s: src/litterale.cpp.s

.PHONY : src/litterale.s

# target to generate assembly for a file
src/litterale.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale.cpp.s
.PHONY : src/litterale.cpp.s

src/litterale_complexe.o: src/litterale_complexe.cpp.o

.PHONY : src/litterale_complexe.o

# target to build an object file
src/litterale_complexe.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_complexe.cpp.o
.PHONY : src/litterale_complexe.cpp.o

src/litterale_complexe.i: src/litterale_complexe.cpp.i

.PHONY : src/litterale_complexe.i

# target to preprocess a source file
src/litterale_complexe.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_complexe.cpp.i
.PHONY : src/litterale_complexe.cpp.i

src/litterale_complexe.s: src/litterale_complexe.cpp.s

.PHONY : src/litterale_complexe.s

# target to generate assembly for a file
src/litterale_complexe.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_complexe.cpp.s
.PHONY : src/litterale_complexe.cpp.s

src/litterale_entiere.o: src/litterale_entiere.cpp.o

.PHONY : src/litterale_entiere.o

# target to build an object file
src/litterale_entiere.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_entiere.cpp.o
.PHONY : src/litterale_entiere.cpp.o

src/litterale_entiere.i: src/litterale_entiere.cpp.i

.PHONY : src/litterale_entiere.i

# target to preprocess a source file
src/litterale_entiere.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_entiere.cpp.i
.PHONY : src/litterale_entiere.cpp.i

src/litterale_entiere.s: src/litterale_entiere.cpp.s

.PHONY : src/litterale_entiere.s

# target to generate assembly for a file
src/litterale_entiere.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_entiere.cpp.s
.PHONY : src/litterale_entiere.cpp.s

src/litterale_rationnelle.o: src/litterale_rationnelle.cpp.o

.PHONY : src/litterale_rationnelle.o

# target to build an object file
src/litterale_rationnelle.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_rationnelle.cpp.o
.PHONY : src/litterale_rationnelle.cpp.o

src/litterale_rationnelle.i: src/litterale_rationnelle.cpp.i

.PHONY : src/litterale_rationnelle.i

# target to preprocess a source file
src/litterale_rationnelle.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_rationnelle.cpp.i
.PHONY : src/litterale_rationnelle.cpp.i

src/litterale_rationnelle.s: src/litterale_rationnelle.cpp.s

.PHONY : src/litterale_rationnelle.s

# target to generate assembly for a file
src/litterale_rationnelle.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_rationnelle.cpp.s
.PHONY : src/litterale_rationnelle.cpp.s

src/litterale_reelle.o: src/litterale_reelle.cpp.o

.PHONY : src/litterale_reelle.o

# target to build an object file
src/litterale_reelle.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_reelle.cpp.o
.PHONY : src/litterale_reelle.cpp.o

src/litterale_reelle.i: src/litterale_reelle.cpp.i

.PHONY : src/litterale_reelle.i

# target to preprocess a source file
src/litterale_reelle.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_reelle.cpp.i
.PHONY : src/litterale_reelle.cpp.i

src/litterale_reelle.s: src/litterale_reelle.cpp.s

.PHONY : src/litterale_reelle.s

# target to generate assembly for a file
src/litterale_reelle.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/litterale_reelle.cpp.s
.PHONY : src/litterale_reelle.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/operateur.o: src/operateur.cpp.o

.PHONY : src/operateur.o

# target to build an object file
src/operateur.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/operateur.cpp.o
.PHONY : src/operateur.cpp.o

src/operateur.i: src/operateur.cpp.i

.PHONY : src/operateur.i

# target to preprocess a source file
src/operateur.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/operateur.cpp.i
.PHONY : src/operateur.cpp.i

src/operateur.s: src/operateur.cpp.s

.PHONY : src/operateur.s

# target to generate assembly for a file
src/operateur.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/operateur.cpp.s
.PHONY : src/operateur.cpp.s

src/operateur_binaire.o: src/operateur_binaire.cpp.o

.PHONY : src/operateur_binaire.o

# target to build an object file
src/operateur_binaire.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/operateur_binaire.cpp.o
.PHONY : src/operateur_binaire.cpp.o

src/operateur_binaire.i: src/operateur_binaire.cpp.i

.PHONY : src/operateur_binaire.i

# target to preprocess a source file
src/operateur_binaire.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/operateur_binaire.cpp.i
.PHONY : src/operateur_binaire.cpp.i

src/operateur_binaire.s: src/operateur_binaire.cpp.s

.PHONY : src/operateur_binaire.s

# target to generate assembly for a file
src/operateur_binaire.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/operateur_binaire.cpp.s
.PHONY : src/operateur_binaire.cpp.s

src/operateur_unaire.o: src/operateur_unaire.cpp.o

.PHONY : src/operateur_unaire.o

# target to build an object file
src/operateur_unaire.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/operateur_unaire.cpp.o
.PHONY : src/operateur_unaire.cpp.o

src/operateur_unaire.i: src/operateur_unaire.cpp.i

.PHONY : src/operateur_unaire.i

# target to preprocess a source file
src/operateur_unaire.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/operateur_unaire.cpp.i
.PHONY : src/operateur_unaire.cpp.i

src/operateur_unaire.s: src/operateur_unaire.cpp.s

.PHONY : src/operateur_unaire.s

# target to generate assembly for a file
src/operateur_unaire.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/operateur_unaire.cpp.s
.PHONY : src/operateur_unaire.cpp.s

src/pile.o: src/pile.cpp.o

.PHONY : src/pile.o

# target to build an object file
src/pile.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/pile.cpp.o
.PHONY : src/pile.cpp.o

src/pile.i: src/pile.cpp.i

.PHONY : src/pile.i

# target to preprocess a source file
src/pile.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/pile.cpp.i
.PHONY : src/pile.cpp.i

src/pile.s: src/pile.cpp.s

.PHONY : src/pile.s

# target to generate assembly for a file
src/pile.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/pile.cpp.s
.PHONY : src/pile.cpp.s

src/qcalculateur.o: src/qcalculateur.cpp.o

.PHONY : src/qcalculateur.o

# target to build an object file
src/qcalculateur.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/qcalculateur.cpp.o
.PHONY : src/qcalculateur.cpp.o

src/qcalculateur.i: src/qcalculateur.cpp.i

.PHONY : src/qcalculateur.i

# target to preprocess a source file
src/qcalculateur.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/qcalculateur.cpp.i
.PHONY : src/qcalculateur.cpp.i

src/qcalculateur.s: src/qcalculateur.cpp.s

.PHONY : src/qcalculateur.s

# target to generate assembly for a file
src/qcalculateur.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/qcalculateur.cpp.s
.PHONY : src/qcalculateur.cpp.s

src/qclavier.o: src/qclavier.cpp.o

.PHONY : src/qclavier.o

# target to build an object file
src/qclavier.cpp.o:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/qclavier.cpp.o
.PHONY : src/qclavier.cpp.o

src/qclavier.i: src/qclavier.cpp.i

.PHONY : src/qclavier.i

# target to preprocess a source file
src/qclavier.cpp.i:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/qclavier.cpp.i
.PHONY : src/qclavier.cpp.i

src/qclavier.s: src/qclavier.cpp.s

.PHONY : src/qclavier.s

# target to generate assembly for a file
src/qclavier.cpp.s:
	$(MAKE) -f CMakeFiles/UTCalculateur.dir/build.make CMakeFiles/UTCalculateur.dir/src/qclavier.cpp.s
.PHONY : src/qclavier.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... UTCalculateur"
	@echo "... UTCalculateur_autogen"
	@echo "... UTCalculateur_autogen/mocs_compilation.o"
	@echo "... UTCalculateur_autogen/mocs_compilation.i"
	@echo "... UTCalculateur_autogen/mocs_compilation.s"
	@echo "... src/controleur.o"
	@echo "... src/controleur.i"
	@echo "... src/controleur.s"
	@echo "... src/litterale.o"
	@echo "... src/litterale.i"
	@echo "... src/litterale.s"
	@echo "... src/litterale_complexe.o"
	@echo "... src/litterale_complexe.i"
	@echo "... src/litterale_complexe.s"
	@echo "... src/litterale_entiere.o"
	@echo "... src/litterale_entiere.i"
	@echo "... src/litterale_entiere.s"
	@echo "... src/litterale_rationnelle.o"
	@echo "... src/litterale_rationnelle.i"
	@echo "... src/litterale_rationnelle.s"
	@echo "... src/litterale_reelle.o"
	@echo "... src/litterale_reelle.i"
	@echo "... src/litterale_reelle.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/operateur.o"
	@echo "... src/operateur.i"
	@echo "... src/operateur.s"
	@echo "... src/operateur_binaire.o"
	@echo "... src/operateur_binaire.i"
	@echo "... src/operateur_binaire.s"
	@echo "... src/operateur_unaire.o"
	@echo "... src/operateur_unaire.i"
	@echo "... src/operateur_unaire.s"
	@echo "... src/pile.o"
	@echo "... src/pile.i"
	@echo "... src/pile.s"
	@echo "... src/qcalculateur.o"
	@echo "... src/qcalculateur.i"
	@echo "... src/qcalculateur.s"
	@echo "... src/qclavier.o"
	@echo "... src/qclavier.i"
	@echo "... src/qclavier.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

